<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>abaqus.Sketcher.ConstrainedSketchGeometry package &mdash; pyabaqus 1.0.5 documentation</title>
      <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
      <link rel="stylesheet" href="../_static/css/theme.css" type="text/css" />
  <!--[if lt IE 9]>
    <script src="../_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
        <script data-url_root="../" id="documentation_options" src="../_static/documentation_options.js"></script>
        <script src="../_static/jquery.js"></script>
        <script src="../_static/underscore.js"></script>
        <script src="../_static/doctools.js"></script>
    <script src="../_static/js/theme.js"></script>
    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Search" href="../search.html" /> 
</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
            <a href="../index.html" class="icon icon-home"> pyabaqus
          </a>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <p class="caption" role="heading"><span class="caption-text">Contents</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="../getting_started.html">Getting Started</a></li>
<li class="toctree-l1"><a class="reference internal" href="../tutorials.html">Tutorials</a></li>
<li class="toctree-l1"><a class="reference internal" href="../references.html">Reference manual</a></li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="Mobile navigation menu" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../index.html">pyabaqus</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="Page navigation">
  <ul class="wy-breadcrumbs">
      <li><a href="../index.html" class="icon icon-home"></a> &raquo;</li>
      <li>abaqus.Sketcher.ConstrainedSketchGeometry package</li>
      <li class="wy-breadcrumbs-aside">
            <a href="../_sources/apidoc/abaqus.Sketcher.ConstrainedSketchGeometry.rst.txt" rel="nofollow"> View page source</a>
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <div class="section" id="abaqus-sketcher-constrainedsketchgeometry-package">
<h1>abaqus.Sketcher.ConstrainedSketchGeometry package<a class="headerlink" href="#abaqus-sketcher-constrainedsketchgeometry-package" title="Permalink to this headline"></a></h1>
<div class="section" id="submodules">
<h2>Submodules<a class="headerlink" href="#submodules" title="Permalink to this headline"></a></h2>
</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.Arc3Points">
<span id="abaqus-sketcher-constrainedsketchgeometry-arc3points-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.Arc3Points module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.Arc3Points" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.Arc3Points.Arc3Points">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.Arc3Points.</span></span><span class="sig-name descname"><span class="pre">Arc3Points</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point3</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.Arc3Points.Arc3Points" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.ArcByCenterEnds">
<span id="abaqus-sketcher-constrainedsketchgeometry-arcbycenterends-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.ArcByCenterEnds module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.ArcByCenterEnds" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ArcByCenterEnds.ArcByCenterEnds">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ArcByCenterEnds.</span></span><span class="sig-name descname"><span class="pre">ArcByCenterEnds</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">center</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">direction</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.SymbolicConstantType</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ArcByCenterEnds.ArcByCenterEnds" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.ArcByStartEndTangent">
<span id="abaqus-sketcher-constrainedsketchgeometry-arcbystartendtangent-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.ArcByStartEndTangent module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.ArcByStartEndTangent" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ArcByStartEndTangent.ArcByStartEndTangent">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ArcByStartEndTangent.</span></span><span class="sig-name descname"><span class="pre">ArcByStartEndTangent</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">vector</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ArcByStartEndTangent.ArcByStartEndTangent" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.CircleByCenterPerimeter">
<span id="abaqus-sketcher-constrainedsketchgeometry-circlebycenterperimeter-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.CircleByCenterPerimeter module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.CircleByCenterPerimeter" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.CircleByCenterPerimeter.CircleByCenterPerimeter">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.CircleByCenterPerimeter.</span></span><span class="sig-name descname"><span class="pre">CircleByCenterPerimeter</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">center</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.CircleByCenterPerimeter.CircleByCenterPerimeter" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry">
<span id="abaqus-sketcher-constrainedsketchgeometry-constrainedsketchgeometry-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.</span></span><span class="sig-name descname"><span class="pre">ConstrainedSketchGeometry</span></span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <code class="xref py py-class docutils literal notranslate"><span class="pre">object</span></code></p>
<p>The ConstrainedSketchGeometry object stores the geometry of a sketch, such as lines,
circles, arcs, and construction lines.</p>
<blockquote>
<div><ul class="simple">
<li><p>import sketch</p></li>
<li><p>mdb.models[name].sketches[name].geometry[i]</p></li>
<li><p>mdb.models[name].sketches[name].geometry[i][i]</p></li>
</ul>
</div></blockquote>
<dl class="py attribute">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry.curveType">
<span class="sig-name descname"><span class="pre">curveType</span></span><em class="property"><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="pre">abaqusConstants.SymbolicConstantType</span></em><em class="property"><span class="w"> </span><span class="p"><span class="pre">=</span></span><span class="w"> </span><span class="pre">None</span></em><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry.curveType" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry.id">
<span class="sig-name descname"><span class="pre">id</span></span><em class="property"><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="pre">int</span></em><em class="property"><span class="w"> </span><span class="p"><span class="pre">=</span></span><span class="w"> </span><span class="pre">None</span></em><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry.id" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry.pointOn">
<span class="sig-name descname"><span class="pre">pointOn</span></span><em class="property"><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="pre">float</span></em><em class="property"><span class="w"> </span><span class="p"><span class="pre">=</span></span><span class="w"> </span><span class="pre">None</span></em><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry.pointOn" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry.type">
<span class="sig-name descname"><span class="pre">type</span></span><em class="property"><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="pre">abaqusConstants.SymbolicConstantType</span></em><em class="property"><span class="w"> </span><span class="p"><span class="pre">=</span></span><span class="w"> </span><span class="pre">None</span></em><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry.type" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel">
<span id="abaqus-sketcher-constrainedsketchgeometry-constrainedsketchgeometrymodel-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.</span></span><span class="sig-name descname"><span class="pre">ConstrainedSketchGeometryModel</span></span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="../sketcher.html#abaqus.Sketcher.ConstrainedSketchBase.ConstrainedSketchBase" title="abaqus.Sketcher.ConstrainedSketchBase.ConstrainedSketchBase"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchBase.ConstrainedSketchBase</span></code></a></p>
<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.Arc3Points">
<span class="sig-name descname"><span class="pre">Arc3Points</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point3</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.Arc3Points" title="Permalink to this definition"></a></dt>
<dd><p>This method constructs an arc using a two endpoints and an intermediate third point on
the arc.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].Arc3Points</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>point1</strong> – A pair of Floats specifying the first endpoint of the arc.</p></li>
<li><p><strong>point2</strong> – A pair of Floats specifying the second endpoint of the arc.</p></li>
<li><p><strong>point3</strong> – A pair of Floats specifying the third point on the arc.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p><strong>geometry</strong> – A ConstrainedSketchGeometry object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">ConstrainedSketchGeometry</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.ArcByCenterEnds">
<span class="sig-name descname"><span class="pre">ArcByCenterEnds</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">center</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">direction</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.SymbolicConstantType</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.ArcByCenterEnds" title="Permalink to this definition"></a></dt>
<dd><p>This method constructs an arc using a center point and two vertices. The Arc object is
added to the geometry repository of the ConstrainedSketch object. The arc is created in
a clockwise fashion from <em>point1</em> to <em>point2</em>.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].ArcByCenterEnds</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>center</strong> – A pair of Floats specifying the center point of the arc.</p></li>
<li><p><strong>point1</strong> – A pair of Floats specifying the first endpoint of the arc.</p></li>
<li><p><strong>point2</strong> – A pair of Floats specifying the second endpoint of the arc.</p></li>
<li><p><strong>direction</strong> – A SymbolicConstant specifying the direction of the arc. Possible values are CLOCKWISE
and COUNTERCLOCKWISE.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p><ul class="simple">
<li><p><strong>geometry</strong> (<code class="xref py py-class docutils literal notranslate"><span class="pre">ConstrainedSketchGeometry</span></code>) – A ConstrainedSketchGeometry object</p></li>
<li><p><code class="xref py py-class docutils literal notranslate"><span class="pre">Exceptions</span></code></p></li>
<li><p><code class="xref py py-class docutils literal notranslate"><span class="pre">----------</span></code> – If incompatible data are given, the second endpoint is ignored</p></li>
</ul>
</p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.ArcByStartEndTangent">
<span class="sig-name descname"><span class="pre">ArcByStartEndTangent</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">vector</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.ArcByStartEndTangent" title="Permalink to this definition"></a></dt>
<dd><p>This method constructs an arc using two vertices. The Arc object is added to the
geometry repository of the ConstrainedSketch object.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].ArcByStartEndTangent</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>point1</strong> – A pair of Floats specifying the first endpoint of the arc.</p></li>
<li><p><strong>point2</strong> – A pair of Floats specifying the second endpoint of the arc.</p></li>
<li><p><strong>vector</strong> – A sequence of two Floats specifying the start direction for constructing the arc.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p><strong>geometry</strong> – A ConstrainedSketchGeometry object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">ConstrainedSketchGeometry</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.CircleByCenterPerimeter">
<span class="sig-name descname"><span class="pre">CircleByCenterPerimeter</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">center</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.CircleByCenterPerimeter" title="Permalink to this definition"></a></dt>
<dd><p>This method constructs a circle using a center point and a point on the perimeter. The
circle is added to the geometry repository of the ConstrainedSketch object.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].CircleByCenterPerimeter</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>center</strong> – A pair of Floats specifying the center point of the circle.</p></li>
<li><p><strong>point1</strong> – A pair of Floats specifying a point on the perimeter of the circle.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p><strong>geometry</strong> – A ConstrainedSketchGeometry object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">ConstrainedSketchGeometry</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.ConstructionCircleByCenterPerimeter">
<span class="sig-name descname"><span class="pre">ConstructionCircleByCenterPerimeter</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">center</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.ConstructionCircleByCenterPerimeter" title="Permalink to this definition"></a></dt>
<dd><p>This method constructs a construction circle using a center point and a point on the
perimeter. The circle is added to the geometry repository of the ConstrainedSketch
object.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].ConstructionCircleByCenterPerimeter</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>center</strong> – A pair of Floats specifying the center point of the construction circle.</p></li>
<li><p><strong>point1</strong> – A pair of Floats specifying a point on the perimeter of the construction circle.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p><strong>geometry</strong> – A ConstrainedSketchGeometry object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">ConstrainedSketchGeometry</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.ConstructionLine">
<span class="sig-name descname"><span class="pre">ConstructionLine</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.ConstructionLine" title="Permalink to this definition"></a></dt>
<dd><p>This method creates an oblique construction line that runs between two given points.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].ConstructionLine</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>point1</strong> – A pair of Floats specifying the first endpoint.</p></li>
<li><p><strong>point2</strong> – A pair of Floats specifying the second endpoint.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p><strong>geometry</strong> – A ConstrainedSketchGeometry object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">ConstrainedSketchGeometry</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.EllipseByCenterPerimeter">
<span class="sig-name descname"><span class="pre">EllipseByCenterPerimeter</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">center</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">axisPoint1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">axisPoint2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.EllipseByCenterPerimeter" title="Permalink to this definition"></a></dt>
<dd><p>This method constructs an ellipse using a center point, a major axis point, and a minor
axis point. The ellipse is added to the geometry repository of the ConstrainedSketch
object.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].EllipseByCenterPerimeter</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>center</strong> – A pair of Floats specifying the center point of the ellipse.</p></li>
<li><p><strong>axisPoint1</strong> – A pair of Floats specifying the major or minor axis point of the ellipse.</p></li>
<li><p><strong>axisPoint2</strong> – A pair of Floats specifying the minor or major axis point of the ellipse.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p><strong>geometry</strong> – A ConstrainedSketchGeometry object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">ConstrainedSketchGeometry</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.FilletByRadius">
<span class="sig-name descname"><span class="pre">FilletByRadius</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">radius</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">curve1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="../sketcher.html#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">nearPoint1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">curve2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="../sketcher.html#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">nearPoint2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.FilletByRadius" title="Permalink to this definition"></a></dt>
<dd><p>This method constructs a fillet arc of a given radius between two curves. The fillet is
added to the geometry repository of the ConstrainedSketch object.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].FilletByRadius</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>radius</strong> – A Float specifying the radius of the fillet arc. Possible values are Floats &gt; 0.</p></li>
<li><p><strong>curve1</strong> – A ConstrainedSketchGeometry object specifying the first curve.</p></li>
<li><p><strong>nearPoint1</strong> – A pair of Floats specifying a point on the sketch near where the user wishes the fillet
to intersect with <em>curve1</em>. This point does not need to be on*curve1*; it is used as a
hint to draw the fillet.</p></li>
<li><p><strong>curve2</strong> – A ConstrainedSketchGeometry object specifying the second curve.</p></li>
<li><p><strong>nearPoint2</strong> – A pair of Floats specifying a point on the sketch near where the user wishes the fillet
to intersect with <em>curve2</em>. This point does not need to be on <em>curve2</em>; it is used as a
hint to draw the fillet.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p><ul class="simple">
<li><p><strong>geometry</strong> (<code class="xref py py-class docutils literal notranslate"><span class="pre">ConstrainedSketchGeometry</span></code>) – A ConstrainedSketchGeometry object</p></li>
<li><p><code class="xref py py-class docutils literal notranslate"><span class="pre">Exceptions</span></code></p></li>
<li><p><code class="xref py py-class docutils literal notranslate"><span class="pre">----------</span></code> –</p>
<ul>
<li><p>If the radius given cannot be used to create a fillet between the two curves given:
Range Error: cannot construct the Fillet specified</p></li>
</ul>
</li>
</ul>
</p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.Line">
<span class="sig-name descname"><span class="pre">Line</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.Line" title="Permalink to this definition"></a></dt>
<dd><p>This method creates a line between two given points.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].Line</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>point1</strong> – A pair of Floats specifying the first endpoint.</p></li>
<li><p><strong>point2</strong> – A pair of Floats specifying the second endpoint.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p><strong>geometry</strong> – A ConstrainedSketchGeometry object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">ConstrainedSketchGeometry</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.Spline">
<span class="sig-name descname"><span class="pre">Spline</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">points</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">constrainPoints</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">True</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.Spline" title="Permalink to this definition"></a></dt>
<dd><p>This method creates a spline curve running through a sequence of points.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].Spline</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>points</strong> – A sequence of pairs of Floats specifying the points through which the spline passes.</p></li>
<li><p><strong>constrainPoints</strong> – A Boolean that determines whether the points given are to constrained to always remain
on the Spline. The default is True. For a large sequence of <em>points</em>, significant
performance gains may be achieved by setting the value to False.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p><strong>geometry</strong> – A ConstrainedSketchGeometry object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">ConstrainedSketchGeometry</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.Spot">
<span class="sig-name descname"><span class="pre">Spot</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.Spot" title="Permalink to this definition"></a></dt>
<dd><p>This method creates a spot construction point located at the specified coordinates. The
spot is added to the vertex repository of the ConstrainedSketch object.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].Spot</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><p><strong>point</strong> – A pair of Floats specifying the coordinates of the spot construction point.</p>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p><strong>geometry</strong> – A ConstrainedSketchGeometry object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">ConstrainedSketchGeometry</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.getPointAtDistance">
<span class="sig-name descname"><span class="pre">getPointAtDistance</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">distance</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">percentage</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.getPointAtDistance" title="Permalink to this definition"></a></dt>
<dd><p>This method returns a point offset along the given ConstrainedSketchGeometry from the
given end by a specified arc length distance or a percentage of the total length of the
ConstrainedSketchGeometry object.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>point</strong> – A pair of Floats specifying the point from which the distance is to be measured.</p></li>
<li><p><strong>distance</strong> – A float specifying the arc length distance along the ConstrainedSketchGeometry from the
<em>point</em> at which the required point is situated.</p></li>
<li><p><strong>percentage</strong> – A Boolean that specifies if the <em>distance</em> is an absolute distance or is a fraction
relative to the length of the ConstrainedSketchGeometry object.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p><strong>points</strong> – A pair of floats representing the point along the edge</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">tuple[float]</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.getSize">
<span class="sig-name descname"><span class="pre">getSize</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.getSize" title="Permalink to this definition"></a></dt>
<dd><p>This method returns the length of the given ConstrainedSketchGeometry object.</p>
<dl class="field-list simple">
<dt class="field-odd">Returns</dt>
<dd class="field-odd"><p><strong>length</strong> – The length of the given ConstrainedSketchGeometry</p>
</dd>
<dt class="field-even">Return type</dt>
<dd class="field-even"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">int</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.getVertices">
<span class="sig-name descname"><span class="pre">getVertices</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometryModel.ConstrainedSketchGeometryModel.getVertices" title="Permalink to this definition"></a></dt>
<dd><p>This method returns an list of ConstrainedSketchVertex objects which are a part of the
given ConstrainedSketchGeometry object.</p>
<dl class="field-list simple">
<dt class="field-odd">Returns</dt>
<dd class="field-odd"><p><strong>vertices</strong> – A list of ConstrainedSketchVertex objects</p>
</dd>
<dt class="field-even">Return type</dt>
<dd class="field-even"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">list[ConstrainedSketchVertex]</span></code></p>
</dd>
</dl>
</dd></dl>

</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.ConstructionCircleByCenterPerimeter">
<span id="abaqus-sketcher-constrainedsketchgeometry-constructioncirclebycenterperimeter-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.ConstructionCircleByCenterPerimeter module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.ConstructionCircleByCenterPerimeter" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstructionCircleByCenterPerimeter.ConstructionCircleByCenterPerimeter">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstructionCircleByCenterPerimeter.</span></span><span class="sig-name descname"><span class="pre">ConstructionCircleByCenterPerimeter</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">center</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstructionCircleByCenterPerimeter.ConstructionCircleByCenterPerimeter" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.ConstructionLine">
<span id="abaqus-sketcher-constrainedsketchgeometry-constructionline-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.ConstructionLine module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.ConstructionLine" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.ConstructionLine.ConstructionLine">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstructionLine.</span></span><span class="sig-name descname"><span class="pre">ConstructionLine</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstructionLine.ConstructionLine" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.EllipseByCenterPerimeter">
<span id="abaqus-sketcher-constrainedsketchgeometry-ellipsebycenterperimeter-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.EllipseByCenterPerimeter module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.EllipseByCenterPerimeter" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.EllipseByCenterPerimeter.EllipseByCenterPerimeter">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.EllipseByCenterPerimeter.</span></span><span class="sig-name descname"><span class="pre">EllipseByCenterPerimeter</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">center</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">axisPoint1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">axisPoint2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.EllipseByCenterPerimeter.EllipseByCenterPerimeter" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.FilletByRadius">
<span id="abaqus-sketcher-constrainedsketchgeometry-filletbyradius-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.FilletByRadius module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.FilletByRadius" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.FilletByRadius.FilletByRadius">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.FilletByRadius.</span></span><span class="sig-name descname"><span class="pre">FilletByRadius</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">radius</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">curve1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">nearPoint1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">curve2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">nearPoint2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.FilletByRadius.FilletByRadius" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.Line">
<span id="abaqus-sketcher-constrainedsketchgeometry-line-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.Line module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.Line" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.Line.Line">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.Line.</span></span><span class="sig-name descname"><span class="pre">Line</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.Line.Line" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.Spline">
<span id="abaqus-sketcher-constrainedsketchgeometry-spline-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.Spline module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.Spline" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.Spline.Spline">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.Spline.</span></span><span class="sig-name descname"><span class="pre">Spline</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">points</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">constrainPoints</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">True</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.Spline.Spline" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.Spot">
<span id="abaqus-sketcher-constrainedsketchgeometry-spot-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.Spot module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.Spot" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.Spot.Spot">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.Spot.</span></span><span class="sig-name descname"><span class="pre">Spot</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.Spot.Spot" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry.getPointAtDistance">
<span id="abaqus-sketcher-constrainedsketchgeometry-getpointatdistance-module"></span><h2>abaqus.Sketcher.ConstrainedSketchGeometry.getPointAtDistance module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry.getPointAtDistance" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchGeometry.getPointAtDistance.getPointAtDistance">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.getPointAtDistance.</span></span><span class="sig-name descname"><span class="pre">getPointAtDistance</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">distance</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">percentage</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchGeometry.getPointAtDistance.getPointAtDistance" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchGeometry">
<span id="module-contents"></span><h2>Module contents<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchGeometry" title="Permalink to this headline"></a></h2>
</div>
</div>


           </div>
          </div>
          <footer>

  <hr/>

  <div role="contentinfo">
    <p>&#169; Copyright 2022, WANG Hailin.</p>
  </div>

  Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>
    provided by <a href="https://readthedocs.org">Read the Docs</a>.
   

</footer>
        </div>
      </div>
    </section>
  </div>
  <script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>