<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>abaqus.Sketcher.ConstrainedSketchDimension package &mdash; pyabaqus 1.0.5 documentation</title>
      <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
      <link rel="stylesheet" href="../_static/css/theme.css" type="text/css" />
  <!--[if lt IE 9]>
    <script src="../_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
        <script data-url_root="../" id="documentation_options" src="../_static/documentation_options.js"></script>
        <script src="../_static/jquery.js"></script>
        <script src="../_static/underscore.js"></script>
        <script src="../_static/doctools.js"></script>
    <script src="../_static/js/theme.js"></script>
    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Search" href="../search.html" /> 
</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
            <a href="../index.html" class="icon icon-home"> pyabaqus
          </a>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <p class="caption" role="heading"><span class="caption-text">Contents</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="../getting_started.html">Getting Started</a></li>
<li class="toctree-l1"><a class="reference internal" href="../tutorials.html">Tutorials</a></li>
<li class="toctree-l1"><a class="reference internal" href="../references.html">Reference manual</a></li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="Mobile navigation menu" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../index.html">pyabaqus</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="Page navigation">
  <ul class="wy-breadcrumbs">
      <li><a href="../index.html" class="icon icon-home"></a> &raquo;</li>
      <li>abaqus.Sketcher.ConstrainedSketchDimension package</li>
      <li class="wy-breadcrumbs-aside">
            <a href="../_sources/apidoc/abaqus.Sketcher.ConstrainedSketchDimension.rst.txt" rel="nofollow"> View page source</a>
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <div class="section" id="abaqus-sketcher-constrainedsketchdimension-package">
<h1>abaqus.Sketcher.ConstrainedSketchDimension package<a class="headerlink" href="#abaqus-sketcher-constrainedsketchdimension-package" title="Permalink to this headline"></a></h1>
<div class="section" id="submodules">
<h2>Submodules<a class="headerlink" href="#submodules" title="Permalink to this headline"></a></h2>
</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchDimension.AngularDimension">
<span id="abaqus-sketcher-constrainedsketchdimension-angulardimension-module"></span><h2>abaqus.Sketcher.ConstrainedSketchDimension.AngularDimension module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchDimension.AngularDimension" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.AngularDimension.AngularDimension">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.AngularDimension.</span></span><span class="sig-name descname"><span class="pre">AngularDimension</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">line1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchGeometry.html#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">line2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchGeometry.html#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">textPoint</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">value</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">reference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.AngularDimension.AngularDimension" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension" title="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension">
<span id="abaqus-sketcher-constrainedsketchdimension-constrainedsketchdimension-module"></span><h2>abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.</span></span><span class="sig-name descname"><span class="pre">ConstrainedSketchDimension</span></span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <code class="xref py py-class docutils literal notranslate"><span class="pre">object</span></code></p>
<p>The ConstrainedSketchDimension object stores the dimensions associated with a sketch.</p>
<blockquote>
<div><ul class="simple">
<li><p>import sketch</p></li>
<li><p>mdb.models[name].sketches[name].dimensions[i]</p></li>
</ul>
</div></blockquote>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel">
<span id="abaqus-sketcher-constrainedsketchdimension-constrainedsketchdimensionmodel-module"></span><h2>abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.</span></span><span class="sig-name descname"><span class="pre">ConstrainedSketchDimensionModel</span></span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="../sketcher.html#abaqus.Sketcher.ConstrainedSketchBase.ConstrainedSketchBase" title="abaqus.Sketcher.ConstrainedSketchBase.ConstrainedSketchBase"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchBase.ConstrainedSketchBase</span></code></a></p>
<p>The ConstrainedSketchDimension object stores the dimensions associated with a sketch.</p>
<blockquote>
<div><ul class="simple">
<li><p>import sketch</p></li>
<li><p>mdb.models[name].sketches[name].dimensions[i]</p></li>
</ul>
</div></blockquote>
<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel.AngularDimension">
<span class="sig-name descname"><span class="pre">AngularDimension</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">line1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchGeometry.html#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">line2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchGeometry.html#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">textPoint</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">value</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">reference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel.AngularDimension" title="Permalink to this definition"></a></dt>
<dd><p>This method constructs a ConstrainedSketchDimension object between two
ConstrainedSketchGeometry objects, with the given angle between them.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].AngularDimension</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>line1</strong> – A ConstrainedSketchGeometry object specifying the first line.</p></li>
<li><p><strong>line2</strong> – A ConstrainedSketchGeometry object specifying the second line.</p></li>
<li><p><strong>textPoint</strong> – A pair of Floats specifying the location of the dimension text.</p></li>
<li><p><strong>value</strong> – A Float specifying the angle between the two lines.</p></li>
<li><p><strong>reference</strong> – A Boolean specifying whether the created dimension enforces the above value or if it
simply measures the angle between two lines.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p>A ConstrainedSketchDimension object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">dimension</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel.DistanceDimension">
<span class="sig-name descname"><span class="pre">DistanceDimension</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">entity1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">entity2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">textPoint</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">value</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">reference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel.DistanceDimension" title="Permalink to this definition"></a></dt>
<dd><p>This method constructs a ConstrainedSketchDimension object between two
ConstrainedSketchGeometry, or aConstrainedSketchVertex and ConstrainedSketchGeometry
object. A distance dimension specifies the shortest distance between two entities.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].DistanceDimension</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>entity1</strong> – A ConstrainedSketchVertex object or ConstrainedSketchGeometry object.</p></li>
<li><p><strong>entity2</strong> – A ConstrainedSketchVertex object or ConstrainedSketchGeometry object.</p></li>
<li><p><strong>textPoint</strong> – A pair of Floats specifying the location of the dimension text.</p></li>
<li><p><strong>value</strong> – A Float specifying the angle between the two lines.</p></li>
<li><p><strong>reference</strong> – A Boolean specifying whether the created dimension enforces the above value or if it
simply measures the angle between two lines.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p>A ConstrainedSketchDimension object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">dimension</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel.HorizontalDimension">
<span class="sig-name descname"><span class="pre">HorizontalDimension</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">vertex1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">vertex2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">textPoint</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">value</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">reference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel.HorizontalDimension" title="Permalink to this definition"></a></dt>
<dd><p>This method constructs a ConstrainedSketchDimension object between two vertices. A
horizontal dimension indicates the horizontal distance along the <em>X</em>-axis between two
vertices.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].HorizontalDimension</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>vertex1</strong> – A ConstrainedSketchVertex object specifying the first endpoint.</p></li>
<li><p><strong>vertex2</strong> – A ConstrainedSketchVertex object specifying the second endpoint.</p></li>
<li><p><strong>textPoint</strong> – A pair of Floats specifying the location of the dimension text.</p></li>
<li><p><strong>value</strong> – A Float distance between the two vertices.</p></li>
<li><p><strong>reference</strong> – A Boolean specifying whether the created dimension enforces the above value or if it
simply measures the distance between the two vertices.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p>A ConstrainedSketchDimension object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">dimension</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel.ObliqueDimension">
<span class="sig-name descname"><span class="pre">ObliqueDimension</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">vertex1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">vertex2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">textPoint</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">value</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">reference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel.ObliqueDimension" title="Permalink to this definition"></a></dt>
<dd><p>This method constructs a ConstrainedSketchDimension object between two vertices. An
oblique dimension indicates the distance between two vertices.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].ObliqueDimension</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>vertex1</strong> – A ConstrainedSketchVertex object specifying the first endpoint.</p></li>
<li><p><strong>vertex2</strong> – A ConstrainedSketchVertex object specifying the second endpoint.</p></li>
<li><p><strong>textPoint</strong> – A pair of Floats specifying the location of the dimension text.</p></li>
<li><p><strong>value</strong> – A Float specifying the distance between the two ConstrainedSketchVertex objects.</p></li>
<li><p><strong>reference</strong> – A Boolean specifying whether the created dimension enforces the above value or if it
simply measures the distance between the two vertices.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p>A ConstrainedSketchDimension object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">dimension</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel.RadialDimension">
<span class="sig-name descname"><span class="pre">RadialDimension</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">curve</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchGeometry.html#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">textPoint</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">value</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">reference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">majorRadius</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">minorRadius</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel.RadialDimension" title="Permalink to this definition"></a></dt>
<dd><p>This method constructs a ConstrainedSketchDimension object on a circular or elliptical
arc. A radial dimension indicates the radius of an arc or circle or the major or minor
radius of an ellipse.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].RadialDimension</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>curve</strong> – A ConstrainedSketchGeometry object specifying the circular or elliptical arc.</p></li>
<li><p><strong>textPoint</strong> – A pair of Floats specifying the location of the dimension text.</p></li>
<li><p><strong>value</strong> – A Float specifying the radius of the arc, circle or ellipse.</p></li>
<li><p><strong>reference</strong> – A Boolean specifying whether the created dimension enforces the above value or if it
simply measures the angle between two lines.</p></li>
<li><p><strong>majorRadius</strong> – A Float specifying the major Radius if <em>curve</em> is an ellipse. This is mutually exclusive
with <em>value</em> and <em>minorRadius</em>.</p></li>
<li><p><strong>minorRadius</strong> – A Float specifying the minor Radius if <em>curve</em> is an ellipse. This is mutually exclusive
with <em>value</em> and <em>majorRadius</em>.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p>A ConstrainedSketchDimension object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">dimension</span></code></p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel.VerticalDimension">
<span class="sig-name descname"><span class="pre">VerticalDimension</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">vertex1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">vertex2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">textPoint</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">value</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">reference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimensionModel.ConstrainedSketchDimensionModel.VerticalDimension" title="Permalink to this definition"></a></dt>
<dd><p>This method constructs a ConstrainedSketchDimension between two vertices. A vertical
dimension controls the vertical distance along the <em>Y</em>-axis between two vertices.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.models[name].sketches[name].VerticalDimension</p></li>
</ul>
</div></blockquote>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>vertex1</strong> – A ConstrainedSketchVertex object specifying the first endpoint.</p></li>
<li><p><strong>vertex2</strong> – A ConstrainedSketchVertex object specifying the second endpoint.</p></li>
<li><p><strong>textPoint</strong> – A pair of Floats specifying the location of the dimension text.</p></li>
<li><p><strong>value</strong> – A Float specifying the angle between the two lines.</p></li>
<li><p><strong>reference</strong> – A Boolean specifying whether the created dimension enforces the above value or if it
simply measures the angle between two lines.</p></li>
</ul>
</dd>
<dt class="field-even">Returns</dt>
<dd class="field-even"><p>A ConstrainedSketchDimension object</p>
</dd>
<dt class="field-odd">Return type</dt>
<dd class="field-odd"><p><code class="xref py py-class docutils literal notranslate"><span class="pre">dimension</span></code></p>
</dd>
</dl>
</dd></dl>

</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchDimension.DistanceDimension">
<span id="abaqus-sketcher-constrainedsketchdimension-distancedimension-module"></span><h2>abaqus.Sketcher.ConstrainedSketchDimension.DistanceDimension module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchDimension.DistanceDimension" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.DistanceDimension.DistanceDimension">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.DistanceDimension.</span></span><span class="sig-name descname"><span class="pre">DistanceDimension</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">entity1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">entity2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">textPoint</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">value</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">reference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.DistanceDimension.DistanceDimension" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension" title="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchDimension.HorizontalDimension">
<span id="abaqus-sketcher-constrainedsketchdimension-horizontaldimension-module"></span><h2>abaqus.Sketcher.ConstrainedSketchDimension.HorizontalDimension module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchDimension.HorizontalDimension" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.HorizontalDimension.HorizontalDimension">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.HorizontalDimension.</span></span><span class="sig-name descname"><span class="pre">HorizontalDimension</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">vertex1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">vertex2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">textPoint</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">value</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">reference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.HorizontalDimension.HorizontalDimension" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension" title="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchDimension.ObliqueDimension">
<span id="abaqus-sketcher-constrainedsketchdimension-obliquedimension-module"></span><h2>abaqus.Sketcher.ConstrainedSketchDimension.ObliqueDimension module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchDimension.ObliqueDimension" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.ObliqueDimension.ObliqueDimension">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.ObliqueDimension.</span></span><span class="sig-name descname"><span class="pre">ObliqueDimension</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">vertex1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">vertex2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">textPoint</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">value</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">reference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.ObliqueDimension.ObliqueDimension" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension" title="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchDimension.RadialDimension">
<span id="abaqus-sketcher-constrainedsketchdimension-radialdimension-module"></span><h2>abaqus.Sketcher.ConstrainedSketchDimension.RadialDimension module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchDimension.RadialDimension" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.RadialDimension.RadialDimension">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.RadialDimension.</span></span><span class="sig-name descname"><span class="pre">RadialDimension</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">curve</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchGeometry.html#abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry" title="abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry"><span class="pre">abaqus.Sketcher.ConstrainedSketchGeometry.ConstrainedSketchGeometry.ConstrainedSketchGeometry</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">textPoint</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">value</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">reference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">majorRadius</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">minorRadius</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.RadialDimension.RadialDimension" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension" title="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchDimension.VerticalDimension">
<span id="abaqus-sketcher-constrainedsketchdimension-verticaldimension-module"></span><h2>abaqus.Sketcher.ConstrainedSketchDimension.VerticalDimension module<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchDimension.VerticalDimension" title="Permalink to this headline"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.Sketcher.ConstrainedSketchDimension.VerticalDimension.VerticalDimension">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.VerticalDimension.</span></span><span class="sig-name descname"><span class="pre">VerticalDimension</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">vertex1</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">vertex2</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="abaqus.Sketcher.ConstrainedSketchVertex.html#abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex" title="abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex"><span class="pre">abaqus.Sketcher.ConstrainedSketchVertex.ConstrainedSketchVertex.ConstrainedSketchVertex</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">textPoint</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">value</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">reference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.Sketcher.ConstrainedSketchDimension.VerticalDimension.VerticalDimension" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension" title="abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension"><code class="xref py py-class docutils literal notranslate"><span class="pre">abaqus.Sketcher.ConstrainedSketchDimension.ConstrainedSketchDimension.ConstrainedSketchDimension</span></code></a></p>
</dd></dl>

</div>
<div class="section" id="module-abaqus.Sketcher.ConstrainedSketchDimension">
<span id="module-contents"></span><h2>Module contents<a class="headerlink" href="#module-abaqus.Sketcher.ConstrainedSketchDimension" title="Permalink to this headline"></a></h2>
</div>
</div>


           </div>
          </div>
          <footer>

  <hr/>

  <div role="contentinfo">
    <p>&#169; Copyright 2022, WANG Hailin.</p>
  </div>

  Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>
    provided by <a href="https://readthedocs.org">Read the Docs</a>.
   

</footer>
        </div>
      </div>
    </section>
  </div>
  <script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>