<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Edit Mesh &mdash; pyabaqus 1.0.9 documentation</title>
      <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
      <link rel="stylesheet" href="../_static/css/theme.css" type="text/css" />
  <!--[if lt IE 9]>
    <script src="../_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
        <script data-url_root="../" id="documentation_options" src="../_static/documentation_options.js"></script>
        <script src="../_static/jquery.js"></script>
        <script src="../_static/underscore.js"></script>
        <script src="../_static/doctools.js"></script>
    <script src="../_static/js/theme.js"></script>
    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Search" href="../search.html" />
    <link rel="next" title="Odb" href="../odb.html" />
    <link rel="prev" title="Annotation" href="annotation.html" /> 
</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
            <a href="../index.html" class="icon icon-home"> pyabaqus
          </a>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <p class="caption" role="heading"><span class="caption-text">Contents</span></p>
<ul class="current">
<li class="toctree-l1"><a class="reference internal" href="../getting_started.html">Getting Started</a></li>
<li class="toctree-l1"><a class="reference internal" href="../tutorials.html">Tutorials</a></li>
<li class="toctree-l1 current"><a class="reference internal" href="../references.html">Reference manual</a><ul class="current">
<li class="toctree-l2 current"><a class="reference internal" href="../mdb.html">Mdb</a><ul class="current">
<li class="toctree-l3"><a class="reference internal" href="model.html">Model</a></li>
<li class="toctree-l3"><a class="reference internal" href="job.html">Job</a></li>
<li class="toctree-l3"><a class="reference internal" href="annotation.html">Annotation</a></li>
<li class="toctree-l3 current"><a class="current reference internal" href="#">Edit Mesh</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#object-features">Object features</a><ul>
<li class="toctree-l5"><a class="reference internal" href="#edit-mesh-features-of-assembly">Edit mesh features of Assembly</a></li>
<li class="toctree-l5"><a class="reference internal" href="#edit-mesh-features-of-part">Edit mesh features of Part</a></li>
<li class="toctree-l5"><a class="reference internal" href="#mesheditoptions">MeshEditOptions</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="../mdb.html#attributes">Attributes</a></li>
<li class="toctree-l3"><a class="reference internal" href="../mdb.html#create-models">Create models</a></li>
<li class="toctree-l3"><a class="reference internal" href="../mdb.html#open-third-party-files">Open third-party files</a></li>
<li class="toctree-l3"><a class="reference internal" href="../mdb.html#create-jobs">Create jobs</a></li>
<li class="toctree-l3"><a class="reference internal" href="../mdb.html#object-features">Object features</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="../odb.html">Odb</a></li>
<li class="toctree-l2"><a class="reference internal" href="../session.html">Session</a></li>
<li class="toctree-l2"><a class="reference internal" href="../kernel.html">Kernel Commands</a></li>
</ul>
</li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="Mobile navigation menu" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../index.html">pyabaqus</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="Page navigation">
  <ul class="wy-breadcrumbs">
      <li><a href="../index.html" class="icon icon-home"></a> &raquo;</li>
          <li><a href="../references.html">Reference manual</a> &raquo;</li>
          <li><a href="../mdb.html">Mdb</a> &raquo;</li>
      <li>Edit Mesh</li>
      <li class="wy-breadcrumbs-aside">
            <a href="../_sources/mdb/edit_mesh.rst.txt" rel="nofollow"> View page source</a>
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <div class="section" id="edit-mesh">
<h1>Edit Mesh<a class="headerlink" href="#edit-mesh" title="Permalink to this headline"></a></h1>
<p>Edit mesh commands are used to edit an orphan mesh part or part instance or an Abaqus native mesh.</p>
<div class="section" id="object-features">
<h2>Object features<a class="headerlink" href="#object-features" title="Permalink to this headline"></a></h2>
<div class="section" id="edit-mesh-features-of-assembly">
<h3>Edit mesh features of Assembly<a class="headerlink" href="#edit-mesh-features-of-assembly" title="Permalink to this headline"></a></h3>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">MeshEditAssembly</span></span><a class="headerlink" href="#abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly" title="Permalink to this definition"></a></dt>
<dd><p>The following commands operate on Assembly objects. For more information about the
Assembly object, see Assembly object.</p>
<blockquote>
<div><ul class="simple">
<li><p>import meshEdit</p></li>
</ul>
</div></blockquote>
<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.collapseMeshEdge">
<span class="sig-name descname"><span class="pre">collapseMeshEdge</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edge</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">collapseMethod</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.SymbolicConstantType</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.collapseMeshEdge" title="Permalink to this definition"></a></dt>
<dd><p>This method collapses an edge of a quadrilateral or triangular element of a part
instance.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>edge</strong> – A single MeshEdge object specifying the element edge to collapse.</p></li>
<li><p><strong>collapseMethod</strong> – A SymbolicConstant specifying the method used to collapse the edge. Possible values are
FORWARD, REVERSE, and AVERAGE.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.combineElement">
<span class="sig-name descname"><span class="pre">combineElement</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">elements</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.combineElement" title="Permalink to this definition"></a></dt>
<dd><p>This method combines two triangular elements of a part instance.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><p><strong>elements</strong> – A sequence of triangular MeshElement objects specifying the elements to combine.</p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.deleteElement">
<span class="sig-name descname"><span class="pre">deleteElement</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">elements</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><a class="reference internal" href="model/mesh.html#abaqus.Mesh.MeshElement.MeshElement" title="abaqus.Mesh.MeshElement.MeshElement"><span class="pre">abaqus.Mesh.MeshElement.MeshElement</span></a><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">deleteUnreferencedNodes</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.deleteElement" title="Permalink to this definition"></a></dt>
<dd><p>This method deletes the given elements from a part instance. The elements must have been
generated using the bottom-up meshing technique.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>elements</strong> – A sequence of MeshElement objects or a Set object containing elements.</p></li>
<li><p><strong>deleteUnreferencedNodes</strong> – A Boolean specifying whether to delete all those associated nodes that become
unreferenced after the given elements are deleted. The default value is OFF.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.editNode">
<span class="sig-name descname"><span class="pre">editNode</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="pre">nodes:</span> <span class="pre">tuple[abaqus.Mesh.MeshNode.MeshNode],</span> <span class="pre">coordinate1:</span> <span class="pre">Optional[float]</span> <span class="pre">=</span> <span class="pre">None,</span> <span class="pre">coordinate2:</span> <span class="pre">Optional[float]</span> <span class="pre">=</span> <span class="pre">None,</span> <span class="pre">coordinate3:</span> <span class="pre">Optional[float]</span> <span class="pre">=</span> <span class="pre">None,</span> <span class="pre">coordinates:</span> <span class="pre">tuple</span> <span class="pre">=</span> <span class="pre">(),</span> <span class="pre">offset1:</span> <span class="pre">Optional[float]</span> <span class="pre">=</span> <span class="pre">None,</span> <span class="pre">offset2:</span> <span class="pre">Optional[float]</span> <span class="pre">=</span> <span class="pre">None,</span> <span class="pre">offset3:</span> <span class="pre">Optional[float]</span> <span class="pre">=</span> <span class="pre">None,</span> <span class="pre">localCsys:</span> <span class="pre">abaqus.Datum.DatumCsys.DatumCsys</span> <span class="pre">=</span> <span class="pre">&lt;abaqus.Datum.DatumCsys.DatumCsys</span> <span class="pre">object&gt;,</span> <span class="pre">projectToGeometry:</span> <span class="pre">abaqusConstants.BooleanType</span> <span class="pre">=</span> <span class="pre">1</span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.editNode" title="Permalink to this definition"></a></dt>
<dd><p>This method changes the coordinates of the given nodes on a part instance.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>nodes</strong> – A sequence of MeshNode objects or a Set object containing nodes.</p></li>
<li><p><strong>coordinate1</strong> – A Float specifying the value of the first coordinate. If <em>coordinate1</em> and <em>offset1</em> are
unspecified, the existing value does not change.</p></li>
<li><p><strong>coordinate2</strong> – A Float specifying the value of the second coordinate. If <em>coordinate2</em> and <em>offset2</em>
are unspecified, the existing value does not change.</p></li>
<li><p><strong>coordinate3</strong> – A Float specifying the value of the third coordinate. If <em>coordinate3</em> and <em>offset3</em> are
unspecified, the existing value does not change.</p></li>
<li><p><strong>coordinates</strong> – A sequence of three-dimensional coordinate tuples specifying the coordinates for each of
the given nodes. When specified, the number of coordinate tuples must match the number
of given nodes, and be ordered to correspond to the given nodes in <em>ascending order</em>
according to index. Furthermore, <em>coordinate1</em>, <em>coordinate2</em>, <em>coordinate3</em>, <em>offset1</em>,
<em>offset2</em>, or <em>offset3</em> may not be specified.</p></li>
<li><p><strong>offset1</strong> – A Float specifying an offset to apply to the value of the first coordinate of the
specified nodes.</p></li>
<li><p><strong>offset2</strong> – A Float specifying an offset to apply to the value of the second coordinate of the
specified nodes.</p></li>
<li><p><strong>offset3</strong> – A Float specifying an offset to apply to the value of the third coordinate of the
specified nodes.</p></li>
<li><p><strong>localCsys</strong> – A DatumCsys object specifying the local coordinate system. If unspecified, the global
coordinate system will be used.</p></li>
<li><p><strong>projectToGeometry</strong> – A Boolean specifying whether to project nodes back to their original geometry. For
example, if a node is on a face, this method first positions the node at the new
location and then projects it back to the original face. The default value is ON.</p></li>
<li><p><strong>Exceptions</strong> – </p></li>
<li><p><strong>----------</strong> – A coordinate and an offset may not both be specified for the same coordinate component.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.generateMeshByOffset">
<span class="sig-name descname"><span class="pre">generateMeshByOffset</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">region</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="model/part_assembly/region.html#abaqus.Region.Region.Region" title="abaqus.Region.Region.Region"><span class="pre">abaqus.Region.Region.Region</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">meshType</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">totalThickness</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">distanceBetweenLayers</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">numLayers</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">int</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">offsetDirection</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">'OUTWARD'</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">initialOffset</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0.0</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">shareNodes</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">False</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">deleteBaseElements</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">False</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">constantThicknessCorners</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">False</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">extendElementSets</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">False</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.generateMeshByOffset" title="Permalink to this definition"></a></dt>
<dd><p>This method generates a solid or shell mesh from an orphan mesh surface by generating
layers of elements that propagate out normal to the surface boundary.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>region</strong> – A Region object specifying the domain to be offset.</p></li>
<li><p><strong>meshType</strong> – A Symbolic Constant specifying the type of mesh to be generated. Possible values are
SOLID or SHELL.</p></li>
<li><p><strong>totalThickness</strong> – A Float specifying the total thickness of the solid layers. This argument applies only
when <a href="#id1"><span class="problematic" id="id2">*</span></a>meshType*=SOLID.</p></li>
<li><p><strong>distanceBetweenLayers</strong> – A Float specifying the distance between shell layers. This argument applies only when
<a href="#id3"><span class="problematic" id="id4">*</span></a>meshType*=SHELL.</p></li>
<li><p><strong>numLayers</strong> – An Int specifying the number of element layers to be generated.</p></li>
<li><p><strong>offsetDirection</strong> – A Symbolic Constant specifying the direction of the offset. This argument is required
only when the given region relates to a shell mesh. Possible values are OUTWARD, INWARD,
and BOTH. The default value is OUTWARD.</p></li>
<li><p><strong>initialOffset</strong> – A Float specifying the magnitude of the initial offset. The default value is zero.</p></li>
<li><p><strong>shareNodes</strong> – Boolean specifying whether the first layer of nodes should be shared with nodes on the
base surface. The default value is False.</p></li>
<li><p><strong>deleteBaseElements</strong> – A Boolean specifying whether to delete the shell elements after the offset layers are
generated. The default value is False. This argument applies only when <a href="#id5"><span class="problematic" id="id6">*</span></a>meshType*=SHELL.</p></li>
<li><p><strong>constantThicknessCorners</strong> – A Boolean specifying whether to use element-based thickness or nodal-based thickness.
The default value is False.</p></li>
<li><p><strong>extendElementSets</strong> – A Boolean specifying whether existing element sets that include base elements will be
extended to include corresponding offset elements. The default value is False.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.projectNode">
<span class="sig-name descname"><span class="pre">projectNode</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">nodes</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><a class="reference internal" href="model/mesh.html#abaqus.Mesh.MeshNode.MeshNode" title="abaqus.Mesh.MeshNode.MeshNode"><span class="pre">abaqus.Mesh.MeshNode.MeshNode</span></a><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">projectionReference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.projectNode" title="Permalink to this definition"></a></dt>
<dd><p>This method projects the given nodes of a part instance onto a mesh entity, geometric
entity, or a datum object.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>nodes</strong> – A sequence of MeshNode objects to be projected.</p></li>
<li><p><strong>projectionReference</strong> – An object specifying the target for the node projection operation. The
<em>projectionReference</em> can be any one of the following objects: MeshNode, MeshEdge,
MeshFace, ConstrainedSketchVertex, Edge, Face, DatumPoint, DatumAxis, or DatumPlane.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.redoMeshEdit">
<span class="sig-name descname"><span class="pre">redoMeshEdit</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.redoMeshEdit" title="Permalink to this definition"></a></dt>
<dd><p>This method executes the edit mesh or the bottom-up meshing operation most recently
undone by the undoMeshEdit method on an assembly. A redo action must be currently
available for the assembly. This implies that the user must have executed the
undoMeshEdit method on the assembly and that the user has not subsequently executed any
further edit mesh commands on the assembly. It also implies that the user provided a
sufficient cache allowance to store the undo operation.</p>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.splitElement">
<span class="sig-name descname"><span class="pre">splitElement</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">elements</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.splitElement" title="Permalink to this definition"></a></dt>
<dd><p>This method splits quadrilateral elements into triangular elements.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><p><strong>elements</strong> – A sequence of quadrilateral MeshElement objects specifying the elements to split. Each
quadrilateral element is split into two triangular elements by the shorter diagonal.</p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.splitMeshEdge">
<span class="sig-name descname"><span class="pre">splitMeshEdge</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edge</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">parameter</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.splitMeshEdge" title="Permalink to this definition"></a></dt>
<dd><p>This method splits an edge of a quadrilateral or triangular element of a part instance.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>edge</strong> – A single MeshEdge object specifying the element edge to split.</p></li>
<li><p><strong>parameter</strong> – A Float specifying the normalized distance along the <em>edge</em> at which to split. Possible
values are 0.0 &lt;&lt; <em>parameter</em> &lt;&lt; 1.0. The default value is 0.5.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.swapMeshEdge">
<span class="sig-name descname"><span class="pre">swapMeshEdge</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edge</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.swapMeshEdge" title="Permalink to this definition"></a></dt>
<dd><p>This method swaps the diagonal of two adjacent triangular elements of a part instance.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><p><strong>edge</strong> – A single MeshEdge object specifying the element edge to swap.</p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.undoMeshEdit">
<span class="sig-name descname"><span class="pre">undoMeshEdit</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditAssembly.MeshEditAssembly.undoMeshEdit" title="Permalink to this definition"></a></dt>
<dd><p>This method undoes the most recent edit mesh or the bottom-up meshing operation on an
assembly and restores the mesh on the affected part instance to its previous state. An
edit mesh undo action must be available for the assembly. This implies that prior to
executing an edit mesh command on the assembly, the user enabled edit mesh undo with a
sufficient cache allowance to store the edit mesh operation.</p>
</dd></dl>

</dd></dl>

</div>
<div class="section" id="edit-mesh-features-of-part">
<h3>Edit mesh features of Part<a class="headerlink" href="#edit-mesh-features-of-part" title="Permalink to this headline"></a></h3>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">MeshEditPart</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">name</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">dimensionality</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.SymbolicConstantType</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">type</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.SymbolicConstantType</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">twist</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">OFF</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart" title="Permalink to this definition"></a></dt>
<dt class="sig sig-object py">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">MeshEditPart</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">name</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">objectToCopy</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">scale</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">1</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">mirrorPlane</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.SymbolicConstantType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">NONE</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">compressFeatureList</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">OFF</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">separate</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">OFF</span></span></em><span class="sig-paren">)</span></dt>
<dd><p>The following commands operate on Part objects. For more information about the Part
object, see Part object.</p>
<blockquote>
<div><ul class="simple">
<li><p>import meshEdit</p></li>
</ul>
</div></blockquote>
<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.adjustMidsideNode">
<span class="sig-name descname"><span class="pre">adjustMidsideNode</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">cornerNodes</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><span class="pre">abaqus.EditMesh.MeshEditPart.Node</span><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">parameter</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.adjustMidsideNode" title="Permalink to this definition"></a></dt>
<dd><p>This method is used to adjust the midside node of second-order elements of an orphan
mesh part.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>cornerNodes</strong> – A sequence of Node objects specifying the nodes towards which connected midside nodes
will be biased.</p></li>
<li><p><strong>parameter</strong> – A Float specifying the normalized distance along the edge of the midside nodes. Possible
values are 0.0 ≤≤ <em>parameter</em> ≤≤ 1.0, where 0.0 specifies the position of the corner
node. The default value is 0.5.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.cleanMesh">
<span class="sig-name descname"><span class="pre">cleanMesh</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">mergeTolerance</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">growEdges</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">elements</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">''</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">refEdge</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">''</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">thicknessDir</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">float</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">moveLayers</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">False</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.cleanMesh" title="Permalink to this definition"></a></dt>
<dd><p>This method is used to collapse short element edges and delete collapsed elements, or
grow short element edges, on an orphan mesh part composed of linear elements.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>mergeTolerance</strong> – A Float specifying the edge length tolerance. During the operation, edges shorter than
the given tolerance will be collapsed, or grown to the specified length.</p></li>
<li><p><strong>growEdges</strong> – A Boolean specifying whether short element edges will be grown to the specified
tolerance. Default is False, meaning short edges will be collapsed.</p></li>
<li><p><strong>elements</strong> – The elements to consider as the domain for the operation. By default all elements on the
part are considered. The elements may be given as a MeshElementArray, a list of
MeshElement objects, a Set, or a list of Set objects.</p></li>
<li><p><strong>refEdge</strong> – A MeshEdge specifying a reference edge to indicate a topological direction in a
structured mesh that will limit which edges within the element domain are considered.
That is, only edges that are found to be topologically parallel to the given reference
edge will be considered by the operation. By default all edges of the element domain are
considered, unless <em>thicknessDir</em> is specified, in which case the operation will attempt
to determine the topological edges from the thickness direction.</p></li>
<li><p><strong>thicknessDir</strong> – A tuple of two or three Floats indicating a vector along which element edge lengths will
be measured.</p></li>
<li><p><strong>moveLayers</strong> – A Boolean indicating whether element edges will be all grown in the direction of the
thickness vector specified by <em>thicknessDir</em>. This argument is ignored unless
<em>growEdges</em> is True and <em>thicknessDir</em> is provided. When this argument is True the
growth of any given element edge will no longer be constrained by short edges on
neighboring elements, but elements could move from their original positions in cases
where there are multiple adjacent layers of thin elements. The default value is False.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.collapseMeshEdge">
<span class="sig-name descname"><span class="pre">collapseMeshEdge</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edge</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">collapseMethod</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.SymbolicConstantType</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.collapseMeshEdge" title="Permalink to this definition"></a></dt>
<dd><p>This method collapses an edge of a quadrilateral or triangular element of an orphan mesh
part or part instance.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>edge</strong> – A single MeshEdge object specifying the element edge to collapse.</p></li>
<li><p><strong>collapseMethod</strong> – A SymbolicConstant specifying the method used to collapse the edge. Possible values are
FORWARD, REVERSE, and AVERAGE.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.combineElement">
<span class="sig-name descname"><span class="pre">combineElement</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">elements</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.combineElement" title="Permalink to this definition"></a></dt>
<dd><p>This method combines two triangular elements of an orphan mesh part or an Abaqus native
mesh.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><p><strong>elements</strong> – A sequence of triangular MeshElement objects specifying the elements to combine.</p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.convertSolidMeshToShell">
<span class="sig-name descname"><span class="pre">convertSolidMeshToShell</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.convertSolidMeshToShell" title="Permalink to this definition"></a></dt>
<dd><p>This method removes all solid elements from an orphan mesh part and creates triangular
or quadrilateral shell elements along their outer faces.</p>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.deleteElement">
<span class="sig-name descname"><span class="pre">deleteElement</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">elements</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><a class="reference internal" href="model/mesh.html#abaqus.Mesh.MeshElement.MeshElement" title="abaqus.Mesh.MeshElement.MeshElement"><span class="pre">abaqus.Mesh.MeshElement.MeshElement</span></a><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">deleteUnreferencedNodes</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.deleteElement" title="Permalink to this definition"></a></dt>
<dd><p>This method deletes the given elements from an orphan mesh part or an Abaqus native
mesh. If the elements belong to an Abaqus native mesh then the elements must have been
generated using the bottom-up meshing technique.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>elements</strong> – A sequence of MeshElement objects or a Set object containing elements.</p></li>
<li><p><strong>deleteUnreferencedNodes</strong> – A Boolean specifying whether to delete all those associated nodes that become
unreferenced after the given elements are deleted. The default value is OFF.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.deleteNode">
<span class="sig-name descname"><span class="pre">deleteNode</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">nodes</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><a class="reference internal" href="model/mesh.html#abaqus.Mesh.MeshNode.MeshNode" title="abaqus.Mesh.MeshNode.MeshNode"><span class="pre">abaqus.Mesh.MeshNode.MeshNode</span></a><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">deleteUnreferencedNodes</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.deleteNode" title="Permalink to this definition"></a></dt>
<dd><p>This method deletes the given nodes from an orphan mesh part.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>nodes</strong> – A sequence of MeshNode objects or a Set object containing nodes.</p></li>
<li><p><strong>deleteUnreferencedNodes</strong> – A Boolean specifying whether to delete all those associated nodes that become
unreferenced after the given nodes and the connected elements are deleted. The default
value is OFF.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.editNode">
<span class="sig-name descname"><span class="pre">editNode</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="pre">nodes:</span> <span class="pre">tuple[abaqus.Mesh.MeshNode.MeshNode],</span> <span class="pre">coordinate1:</span> <span class="pre">Optional[float]</span> <span class="pre">=</span> <span class="pre">None,</span> <span class="pre">coordinate2:</span> <span class="pre">Optional[float]</span> <span class="pre">=</span> <span class="pre">None,</span> <span class="pre">coordinate3:</span> <span class="pre">Optional[float]</span> <span class="pre">=</span> <span class="pre">None,</span> <span class="pre">coordinates:</span> <span class="pre">tuple</span> <span class="pre">=</span> <span class="pre">(),</span> <span class="pre">offset1:</span> <span class="pre">Optional[float]</span> <span class="pre">=</span> <span class="pre">None,</span> <span class="pre">offset2:</span> <span class="pre">Optional[float]</span> <span class="pre">=</span> <span class="pre">None,</span> <span class="pre">offset3:</span> <span class="pre">Optional[float]</span> <span class="pre">=</span> <span class="pre">None,</span> <span class="pre">localCsys:</span> <span class="pre">abaqus.Datum.DatumCsys.DatumCsys</span> <span class="pre">=</span> <span class="pre">&lt;abaqus.Datum.DatumCsys.DatumCsys</span> <span class="pre">object&gt;,</span> <span class="pre">projectToGeometry:</span> <span class="pre">abaqusConstants.BooleanType</span> <span class="pre">=</span> <span class="pre">1</span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.editNode" title="Permalink to this definition"></a></dt>
<dd><p>This method changes the coordinates of the given nodes on an orphan mesh part or on an
Abaqus native mesh.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>nodes</strong> – A sequence of MeshNode objects or a Set object containing nodes.</p></li>
<li><p><strong>coordinate1</strong> – A Float specifying the value of the first coordinate. If <em>coordinate1</em> and <em>offset1</em> are
unspecified, the existing value does not change.</p></li>
<li><p><strong>coordinate2</strong> – A Float specifying the value of the second coordinate. If <em>coordinate2</em> and <em>offset2</em>
are unspecified, the existing value does not change.</p></li>
<li><p><strong>coordinate3</strong> – A Float specifying the value of the third coordinate. If <em>coordinate3</em> and <em>offset3</em> are
unspecified, the existing value does not change.</p></li>
<li><p><strong>coordinates</strong> – A sequence of three-dimensional coordinate tuples specifying the coordinates for each of
the given nodes. When specified, the number of coordinate tuples must match the number
of given nodes, and be ordered to correspond to the given nodes in <em>ascending order</em>
according to index. Furthermore, <em>coordinate1</em>, <em>coordinate2</em>, <em>coordinate3</em>, <em>offset1</em>,
<em>offset2</em>, or <em>offset3</em> may not be specified.</p></li>
<li><p><strong>offset1</strong> – A Float specifying an offset to apply to the value of the first coordinate of the
specified nodes.</p></li>
<li><p><strong>offset2</strong> – A Float specifying an offset to apply to the value of the second coordinate of the
specified nodes.</p></li>
<li><p><strong>offset3</strong> – A Float specifying an offset to apply to the value of the third coordinate of the
specified nodes.</p></li>
<li><p><strong>localCsys</strong> – A DatumCsys object specifying the local coordinate system. If unspecified, the global
coordinate system will be used.</p></li>
<li><p><strong>projectToGeometry</strong> – A Boolean specifying whether to project nodes back to their original geometry. For
example, if a node is on a face, this method first positions the node at the new
location and then projects it back to the original face. The default value is ON.</p></li>
<li><p><strong>Exceptions</strong> – </p></li>
<li><p><strong>----------</strong> – A coordinate and an offset may not both be specified for the same coordinate component.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.generateMesh">
<span class="sig-name descname"><span class="pre">generateMesh</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">elemShape</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">abaqusConstants.SymbolicConstantType</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.generateMesh" title="Permalink to this definition"></a></dt>
<dd><p>This method generates a new mesh on an orphan mesh part based on the original mesh.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><p><strong>elemShape</strong> – A SymbolicConstant specifying the element shape to be used for meshing. Possible values
are:TRIRefine a planar triangular mesh and replace it with a new one. If no element
sizes are attached, the new mesh will be governed by the sizes of the boundary edges in
the old mesh.TETCreate a tetrahedral mesh from a closed shell of triangular elements.</p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.generateMeshByOffset">
<span class="sig-name descname"><span class="pre">generateMeshByOffset</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">region</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="model/part_assembly/region.html#abaqus.Region.Region.Region" title="abaqus.Region.Region.Region"><span class="pre">abaqus.Region.Region.Region</span></a></span></em>, <em class="sig-param"><span class="n"><span class="pre">meshType</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">totalThickness</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">distanceBetweenLayers</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">numLayers</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">int</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">offsetDirection</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">'OUTWARD'</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">initialOffset</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0.0</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">shareNodes</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">False</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">deleteBaseElements</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">False</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">constantThicknessCorners</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">False</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">extendElementSets</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">False</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.generateMeshByOffset" title="Permalink to this definition"></a></dt>
<dd><p>This method generates a solid or shell mesh from an orphan mesh surface by generating
layers of elements that propagate out normal to the surface boundary.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>region</strong> – A Region object specifying the domain to be offset.</p></li>
<li><p><strong>meshType</strong> – A Symbolic Constant specifying the type of mesh to be generated. Possible values are
SOLID or SHELL.</p></li>
<li><p><strong>totalThickness</strong> – A Float specifying the total thickness of the solid layers. This argument applies only
when <a href="#id7"><span class="problematic" id="id8">*</span></a>meshType*=SOLID.</p></li>
<li><p><strong>distanceBetweenLayers</strong> – A Float specifying the distance between shell layers. This argument applies only when
<a href="#id9"><span class="problematic" id="id10">*</span></a>meshType*=SHELL.</p></li>
<li><p><strong>numLayers</strong> – An Int specifying the number of element layers to be generated.</p></li>
<li><p><strong>offsetDirection</strong> – A Symbolic Constant specifying the direction of the offset. This argument is required
only when the given region relates to a shell mesh. Possible values are OUTWARD, INWARD,
and BOTH. The default value is OUTWARD.</p></li>
<li><p><strong>initialOffset</strong> – A Float specifying the magnitude of the initial offset. The default value is zero.</p></li>
<li><p><strong>shareNodes</strong> – Boolean specifying whether the first layer of nodes should be shared with nodes on the
base surface. The default value is False.</p></li>
<li><p><strong>deleteBaseElements</strong> – A Boolean specifying whether to delete the shell elements after the offset layers are
generated. The default value is False. This argument applies only when <a href="#id11"><span class="problematic" id="id12">*</span></a>meshType*=SHELL.</p></li>
<li><p><strong>constantThicknessCorners</strong> – A Boolean specifying whether to use element-based thickness or nodal-based thickness.
The default value is False.</p></li>
<li><p><strong>extendElementSets</strong> – A Boolean specifying whether existing element sets that include base elements will be
extended to include corresponding offset elements. The default value is False.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.mergeElement">
<span class="sig-name descname"><span class="pre">mergeElement</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edge</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">elements</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.mergeElement" title="Permalink to this definition"></a></dt>
<dd><p>Merge a selection of elements arranged in layers on an orphan mesh part into a single
layer.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>edge</strong> – A MeshEdge of one of the specified elements that serves as a reference edge to indicate
the topological direction for merging elements. All specified elements must be reachable
by topological navigation from this element edge, and the topological direction must be
unambiguous.</p></li>
<li><p><strong>elements</strong> – A MeshElementArray, a list of MeshElement objects, a Set, or a list of Set objects
containing the elements to be included in the merge operation.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.orientElements">
<span class="sig-name descname"><span class="pre">orientElements</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">pickedElements</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><a class="reference internal" href="model/mesh.html#abaqus.Mesh.MeshElement.MeshElement" title="abaqus.Mesh.MeshElement.MeshElement"><span class="pre">abaqus.Mesh.MeshElement.MeshElement</span></a><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">referenceRegion</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><a class="reference internal" href="model/mesh.html#abaqus.Mesh.MeshFace.MeshFace" title="abaqus.Mesh.MeshFace.MeshFace"><span class="pre">abaqus.Mesh.MeshFace.MeshFace</span></a></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.orientElements" title="Permalink to this definition"></a></dt>
<dd><p>This method orients the stack direction of elements in a continuum shell or gasket mesh.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>pickedElements</strong> – A sequence of MeshElement objects specifying the elements to orient.</p></li>
<li><p><strong>referenceRegion</strong> – A MeshFace object specifying a reference top face that indicates the desired
orientation.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.projectNode">
<span class="sig-name descname"><span class="pre">projectNode</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">nodes</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span><span class="p"><span class="pre">[</span></span><a class="reference internal" href="model/mesh.html#abaqus.Mesh.MeshNode.MeshNode" title="abaqus.Mesh.MeshNode.MeshNode"><span class="pre">abaqus.Mesh.MeshNode.MeshNode</span></a><span class="p"><span class="pre">]</span></span></span></em>, <em class="sig-param"><span class="n"><span class="pre">projectionReference</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.projectNode" title="Permalink to this definition"></a></dt>
<dd><p>This method projects the given nodes onto a mesh entity, geometric entity, or a datum
object. The nodes may belong to an orphan mesh part or to an Abaqus native mesh.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>nodes</strong> – A sequence of MeshNode objects to be projected.</p></li>
<li><p><strong>projectionReference</strong> – An object specifying the target for the node projection operation. The
<em>projectionReference</em> can be any one of the following objects: MeshNode, MeshEdge,
MeshFace, ConstrainedSketchVertex, Edge, Face, DatumPoint, DatumAxis, or DatumPlane.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.redoMeshEdit">
<span class="sig-name descname"><span class="pre">redoMeshEdit</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.redoMeshEdit" title="Permalink to this definition"></a></dt>
<dd><p>This method executes the edit mesh or the bottom-up meshing operation most recently
undone by the undoMeshEdit method on an part. A redo action must be currently available
for the part. This implies that the user must have executed the undoMeshEdit method on
the part and that the user has not subsequently executed any further edit mesh commands
on the assembly. It also implies that the user provided a sufficient cache allowance to
store the undo operation.</p>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.removeElementSize">
<span class="sig-name descname"><span class="pre">removeElementSize</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.removeElementSize" title="Permalink to this definition"></a></dt>
<dd><p>This method removes the global element size from an orphan mesh part.</p>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.renumberElement">
<span class="sig-name descname"><span class="pre">renumberElement</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">elements</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">()</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">startLabel</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">int</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">increment</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">int</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">offset</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">int</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">labels</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">''</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.renumberElement" title="Permalink to this definition"></a></dt>
<dd><p>This method assigns new labels to orphan mesh elements.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>elements</strong> – A MeshElementArray or a tuple or list of MeshElement objects, or a Set containing
elements to be renumbered. If unspecified, all elements in the part will be renumbered.</p></li>
<li><p><strong>startLabel</strong> – A positive Int specifying the new label for the first element in <em>elements</em>.</p></li>
<li><p><strong>increment</strong> – A positive Int specifying the increment used for computation of new labels for all
consecutive elements in <em>elements</em>.</p></li>
<li><p><strong>offset</strong> – An Int by which existing labels of the specified elements will be offset.</p></li>
<li><p><strong>labels</strong> – A list of labels for the specified elements. The length of this list must match the
number of specified elements.</p></li>
<li><p><strong>Exceptions</strong> – </p></li>
<li><p><strong>----------</strong> – <ul>
<li><p>Renumbering is attempted on a native part:
Error: Renumbering can be applied to orphan mesh parts only</p></li>
<li><p>Renumbering data is specified incorrectly:
Error: Either startLabel and increment or offset must be specified</p></li>
<li><p>Renumbering will result in invalid labels:
Error: Specified data will result in invalid labels</p></li>
<li><p>Renumbering will result in conflicting labels:
Error: Specified data will result in conflicting labels</p></li>
</ul>
</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.renumberNode">
<span class="sig-name descname"><span class="pre">renumberNode</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">nodes</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">()</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">startLabel</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">int</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">increment</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">int</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">offset</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">Optional</span><span class="p"><span class="pre">[</span></span><span class="pre">int</span><span class="p"><span class="pre">]</span></span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">labels</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">''</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.renumberNode" title="Permalink to this definition"></a></dt>
<dd><p>This method assigns new labels to orphan mesh nodes.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>nodes</strong> – A MeshNodeArray or a tuple or list of MeshNode objects, or a Set containing nodes to be
renumbered. If unspecified, all nodes in the part will be renumbered.</p></li>
<li><p><strong>startLabel</strong> – A positive Int specifying the new label for the first node in <em>nodes</em>.</p></li>
<li><p><strong>increment</strong> – A positive Int specifying the increment used for computation of new labels for all
consecutive nodes in <em>nodes</em>.</p></li>
<li><p><strong>offset</strong> – An Int by which existing labels of the specified nodes will be offset.</p></li>
<li><p><strong>labels</strong> – A list of labels for the specified nodes. The length of this list must match the number
of specified nodes.</p></li>
<li><p><strong>Exceptions</strong> – </p></li>
<li><p><strong>----------</strong> – <ul>
<li><p>Renumbering is attempted on a native part:
Error: Renumbering can be applied to orphan mesh parts only</p></li>
<li><p>Renumbering data is specified incorrectly:
Error: Either startLabel and increment or offset must be specified</p></li>
<li><p>Renumbering will result in invalid labels:
Error: Specified data will result in invalid labels</p></li>
<li><p>Renumbering will result in conflicting labels:
Error: Specified data will result in conflicting labels</p></li>
</ul>
</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.setElementSize">
<span class="sig-name descname"><span class="pre">setElementSize</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">size</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.setElementSize" title="Permalink to this definition"></a></dt>
<dd><p>This method sets the global element size for an orphan mesh part.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><p><strong>size</strong> – A Float specifying the desired element size.</p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.splitElement">
<span class="sig-name descname"><span class="pre">splitElement</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">elements</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">tuple</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.splitElement" title="Permalink to this definition"></a></dt>
<dd><p>This method splits quadrilateral elements of an orphan mesh part or a Abaqus native mesh
into triangular elements.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><p><strong>elements</strong> – A sequence of quadrilateral MeshElement objects specifying the elements to split. Each
quadrilateral element is split into two triangular elements by the shorter diagonal.</p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.splitMeshEdge">
<span class="sig-name descname"><span class="pre">splitMeshEdge</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edge</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">parameter</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.splitMeshEdge" title="Permalink to this definition"></a></dt>
<dd><p>This method splits an edge of a quadrilateral or triangular element of an orphan mesh
part or an Abaqus native mesh.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>edge</strong> – A single MeshEdge object specifying the element edge to split.</p></li>
<li><p><strong>parameter</strong> – A Float specifying the normalized distance along <em>edge</em> at which to split. Possible
values are 0.0 &lt;&lt; <em>parameter</em> &lt;&lt; 1.0. The default value is 0.5.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.subdivideElement">
<span class="sig-name descname"><span class="pre">subdivideElement</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">elements:</span> <span class="pre">str</span> <span class="pre">=</span> <span class="pre">''</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">divisionNumber:</span> <span class="pre">Optional[int]</span> <span class="pre">=</span> <span class="pre">None</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">face:</span> <span class="pre">abaqus.Mesh.MeshFace.MeshFace</span> <span class="pre">=</span> <span class="pre">&lt;abaqus.Mesh.MeshFace.MeshFace</span> <span class="pre">object&gt;</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">edge:</span> <span class="pre">abaqus.Mesh.MeshEdge.MeshEdge</span> <span class="pre">=</span> <span class="pre">&lt;abaqus.Mesh.MeshEdge.MeshEdge</span> <span class="pre">object&gt;</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.subdivideElement" title="Permalink to this definition"></a></dt>
<dd><p>Subdivide a selection of elements on an orphan mesh part in one or more directions.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>elements</strong> – A MeshElementArray, a list of MeshElement objects, a Set, or a list of Set objects
containing the elements to be subdivided. By default all the elements of the part are
subdivided.</p></li>
<li><p><strong>divisionNumber</strong> – An Int specifying the number of resulting elements for each input element in each
direction of the subdivision. If <em>face</em> or <em>edge</em> are not specified, elements will be
subdivided according to this number in all possible directions. Must be greater than
one. Default is 2.</p></li>
<li><p><strong>face</strong> – A MeshFace object that serves as a reference for indicating two topological directions
for the subdivision operation. Must be a face of one of the specified elements, and all
specified elements must be reachable by topological navigation from this element face.
May not be combined with <em>edge</em>.</p></li>
<li><p><strong>edge</strong> – A MeshEdge object that serves as a reference for indicating a single topological
direction for the subdivision operation. Must be an edge of one of the specified
elements, and all specified elements must be reachable by topological navigation from
this element edge. May not be combined with <em>face</em>.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.swapMeshEdge">
<span class="sig-name descname"><span class="pre">swapMeshEdge</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edge</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">str</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.swapMeshEdge" title="Permalink to this definition"></a></dt>
<dd><p>This method swaps the diagonal of two adjacent triangular elements of an orphan mesh
part or an Abaqus native mesh.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><p><strong>edge</strong> – A single MeshEdge object specifying the element edge to swap.</p>
</dd>
</dl>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.undoMeshEdit">
<span class="sig-name descname"><span class="pre">undoMeshEdit</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.undoMeshEdit" title="Permalink to this definition"></a></dt>
<dd><p>This method undoes the most recent edit mesh or the bottom-up meshing operation on a
part and restores the mesh to its previous state. An edit mesh undo action must be
available for the part. This implies that prior to executing an edit mesh command on the
part, the user enabled edit mesh undo with a sufficient cache allowance to store the
edit mesh operation.</p>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditPart.MeshEditPart.wrapMesh">
<span class="sig-name descname"><span class="pre">wrapMesh</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">radius</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditPart.MeshEditPart.wrapMesh" title="Permalink to this definition"></a></dt>
<dd><p>This method wraps a planar orphan mesh part about the <em>Z</em>-axis.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><p><strong>radius</strong> – A Float specifying the radius of the cylinder about which the part is to be wrapped. The
wrapping procedure will relocate a node at point (xx, yy) on the planar mesh to
(x,θ,zx,θ,z), where rr is the specified radius, θθ = xrxr, and zz=yy.</p>
</dd>
</dl>
</dd></dl>

</dd></dl>

</div>
<div class="section" id="mesheditoptions">
<h3>MeshEditOptions<a class="headerlink" href="#mesheditoptions" title="Permalink to this headline"></a></h3>
<dl class="py class">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditOptions.MeshEditOptions">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">MeshEditOptions</span></span><a class="headerlink" href="#abaqus.EditMesh.MeshEditOptions.MeshEditOptions" title="Permalink to this definition"></a></dt>
<dd><p>The MeshEditOptions object stores settings that specify the behavior when editing meshes
on parts or part instances.
The MeshEditOptions object has no constructor. Abaqus creates the <em>MeshEditOptions</em>
member when a session is started.</p>
<blockquote>
<div><ul class="simple">
<li><p>mdb.meshEditOptions</p></li>
</ul>
</div></blockquote>
<dl class="py method">
<dt class="sig sig-object py" id="abaqus.EditMesh.MeshEditOptions.MeshEditOptions.setValues">
<span class="sig-name descname"><span class="pre">setValues</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">maxUndoCacheElements</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">float</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">enableUndo</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">_suspendUndo</span></span><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="n"><span class="pre">abaqusConstants.BooleanType</span></span><span class="w"> </span><span class="o"><span class="pre">=</span></span><span class="w"> </span><span class="default_value"><span class="pre">0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#abaqus.EditMesh.MeshEditOptions.MeshEditOptions.setValues" title="Permalink to this definition"></a></dt>
<dd><p>This method modifies the MeshEditOptions object.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters</dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>maxUndoCacheElements</strong> – A Float specifying the maximum allowable mesh edit undo cache size in millions of
elements. If this value is set to at least the number of elements on a given part or
part instance, at least one level of undo/redo capability is assured for subsequent mesh
edit operations on that part or part instance. The default value is 0.0.</p></li>
<li><p><strong>enableUndo</strong> – A Boolean specifying whether undo/redo of mesh edit operations will be enabled. If
<em>enableUndo</em> =OFF any existing cache for undo/redo operations will be cleared for all
parts and assemblies in all models. The default value is OFF.</p></li>
<li><p><strong>_suspendUndo</strong> – A Boolean specifying the suspension of undo/redo for mesh edit operations. When
undo/redo is suspended, undo/redo will not be available after subsequent mesh edit
operations on a given part or part instances. Any pre-existing cache for mesh edit
operations on other parts or assemblies in any model will be unaffected. The default
value is OFF.If you change the value of <em>enableUndo</em> to True, Abaqus sets <em>_suspendUndo</em>
to False.</p></li>
</ul>
</dd>
</dl>
</dd></dl>

</dd></dl>

</div>
</div>
</div>


           </div>
          </div>
          <footer><div class="rst-footer-buttons" role="navigation" aria-label="Footer">
        <a href="annotation.html" class="btn btn-neutral float-left" title="Annotation" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left" aria-hidden="true"></span> Previous</a>
        <a href="../odb.html" class="btn btn-neutral float-right" title="Odb" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right" aria-hidden="true"></span></a>
    </div>

  <hr/>

  <div role="contentinfo">
    <p>&#169; Copyright 2022, WANG Hailin.</p>
  </div>

  Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>
    provided by <a href="https://readthedocs.org">Read the Docs</a>.
   

</footer>
        </div>
      </div>
    </section>
  </div>
  <script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>